config/routes.rb
Blog::Application.routes.draw do
  resources :posts
  resources :sessions
  resources :users

  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'

  root :to => 'home#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :auth_token, :password
end

app/models/user.rb
class User < ActiveRecord::Base
  #Password and Password_confirmation are just virtual attributes
  has_many :posts
  has_secure_password

  before_create :generate_auth_token
  attr_accessible :email, :full_name, :password, :password_confirmation, :permissions

  validates :full_name, presence: true, length: { maximum: 40 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false }

  def is_admin?
    permissions == 0
  end

  def is_developer?
    permissions == 1
  end

  def is_author?
    permissions == 2
  end

  def permission_str
    case self[:permissions]
      when 0 then "Administrator"
      when 1 then "Developer"
      when 2 then "Author"
    end
  end

  private

  def generate_auth_token
    self.auth_token = SecureRandom.urlsafe_base64 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :signed_in?, :login_user

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end

  def signed_in?
    current_user.present?
  end

  def must_be_signed_in
    redirect_to login_path if !signed_in?
  end

  def login_user(user)
    cookies[:auth_token] = user.auth_token
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :must_be_signed_in, :except => [:index, :show]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 3).order('id DESC')
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      flash[:success] = "Post successful!"
      redirect_to posts_path
    else
      flash.now[:error] = "Something went wrong!"
      render :new
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update.attributes(params[:id])
      flash[:success] = "Post successful!"
      redirect_to @post
    else
      flash[:error] = "Something went wrong!"
      render :new
    end

  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted!"
    redirect_to posts_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to posts_path if signed_in?
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      cookies[:auth_token] = user.auth_token
      redirect_to posts_path
    else
      flash.now[:error] = "Invalid"
      render :new
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user(@user)
      flash[:success] = "Successful"
      redirect_to posts_path
    else
      flash.now[:error] = "Something went wrong!"
      render :new
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.new(params[:id])

    if @user.save
      flash[:success] = "Successful"
      redirect_to posts_path
    else
      flash.now[:error] = "Something went wrong!"
      render :new
    end

  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_time(time)
    time.strftime("%-d %b %Y")
  end
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_url
    gravatar_id = Digest::MD5::hexdigest("petesta@live.com").downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/cd_helper.rb
module CdHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="header-container">
  <div class="header-description">
    <h1> How's it going, I'm Pete! </h1>
    <p>
      I love functional programming and have interests
      in devops and web backends.
    </p>

    <div class="resume">
      <%= link_to "posts#index", class: "btn btn-primary btn-custom btn-blog" do %>
        <i class="fa fa-list-ul"></i>
        Blog
      <% end %>

      <a class="btn btn-primary btn-custom btn-resume" href="/PeteCruz_Resume.pdf" target="_blank">
        <i class="fa fa-file"></i>
        Resume
      </a>
    </div> <!--resume-->
  </div> <!--header-description-->
</section> <!--header-container-->

<div class="social">
  <div class="social-container">
    <div class="social-links">
      <div class="linkedin social-link">
        <a href="http://www.linkedin.com/in/petecruz">
          <i class="fa fa-linkedin-square"></i>
          LinkedIn
        </a>
      </div>

      <div class="github social-link">
        <a href="http://www.github.com/Petesta">
          <i class="fa fa-github"></i>
          Github
        </a>
      </div>

      <div class="twitter social-link">
        <a href="http://www.twitter.com/iPetesta">
          <i class="fa fa-twitter"></i>
          Twitter
        </a>
      </div>
    </div> <!--social-links-->
  </div> <!--social-container-->
</div> <!--social-->

<section class="intro-container">
  <div class="lang-container">
    <h1>Favorite Languages</h1>
    <p> Ruby, Scala, Haskell </p>

    <i class="fa fa-code fa-3x icon"></i>
    <br/>
    <div class="language-info generic-info-container">
      My go to languages are Ruby and Scala for personal projects and rapidly
      prototyping. Lately I've been using Haskell. Used for general backend
      and web apps!
    </div> <!-- language-info-->
  </div> <!--lang-contianer-->

  <hr>

  <div class="backend-container">
    <h1>Web Backends</h1>
    <p> Rails, Play, Unfiltered </p>

    <i class="fa fa-gears fa-3x icon"></i>
    <br/>

    <div class="generic-info-container">
      <div class="generic-info">I love playing with Rails! It allows me to rapidly prototype a project and try out new JavaScript frameworks.</div>
      <div class="generic-info">I've come to enjoy using Play over time. I'm a big fan of type checking already. Although some features could be improved upon.</div>
      <div class="generic-info argonaut">I used Unfiltered at the 2013 Facebook Hackathon at their HQ. It's a micro web framework and easily integrate with
        <a href="http://argonaut.io" id="argonaut">Argonaut</a>.</div>
    </div> <!--generic-info-container-->
  </div> <!--backend-container-->

  <hr>

  <div class="projects-container">
    <h1>Projects</h1>
    <p> Compiler, Geocodr, RingBase </p>

    <i class="fa fa-folder-open fa-3x icon"></i>

    <div class="generic-info-container">
      <div class="generic-info">Built an LR1 compiler that generated x86 bytecode instructions.</div>

      <div class="generic-info">
        <a href="http://ucsb-geocodr.herokuapp.com" id="geocodr">Geocodr</a>
        (Facebook) uses Github's API to find programmers near you and compare interests!
      </div>

      <div class="generic-info">
        <a href="http://www.github.com/RingBase" id="ringbase">RingBase</a>
        is a real-time ad-hoc call center platform. Employees view incoming calls in real-time.
      </div>
    </div> <!--generic-info-container-->
  </div> <!--projects-container-->
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% if controller.controller_name != "home" %>
    <header>
      <%= link_to "Home", "/", class: "btn btn-primary btn-home" %>

      <div class="container">
        <div class="row">
          <div class="header-info span-16">
            <p> Blog : : Petesta -> [ Posts ] </p>
          </div>
        </div>
      </div> <!--container-->
    </header>
  <% end %>

  <div class="page-wrap">
    <%= yield %>
  </div>

  <% if signed_in? %>
    <p> Signed in as <%= current_user.email %> </p>
  <% end %>

  <footer></footer>
</body>
</html>

app/views/posts/_sidebar.html.erb
<div class="span-5 sidebar">
  <center>
    <div class="avatar">
    <%= link_to image_tag(avatar_url), "/" %>
    </div>
  </center>

  <p>
    I'm a computer science major at the University of California, Santa Barbara
    who's a fanatic Vim user and love learning new technologies.
  </p>
</div>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<%= form_for @post do |f| %>
  <% f.label :field %>
  <% f.text_field :field %>

  <% f.label :body %>
  <% f.text_area :body %>

  <% f.submit 'Save Post' %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'posts/sidebar' %>

    <div class="span-10 offset-1 posts-container">
      <% @posts.each do |post| %>
        <div class="post">
          <div class="post-title">
            <h2><%= post.title %></h2>
          </div>

          <p class="post-date"><%= render_time(post.created_at) %></p>

          <div class="post-body">
            <%= post.body %>
          </div>

          <hr>
        </div> <!--post-->
      <% end %>

      <%= will_paginate @posts, :outer_window => 1 %>

      <% if signed_in? %>
        <%= link_to "Create new post", new_post_path, {class: "btn btn-blue", id: "new-post"} %>
      <% end %>
    </div>
  </div> <!--row-->
</div> <!--container-->

app/views/posts/list.html.erb
<h1>Posts#list</h1>

app/views/posts/new.html.erb
<div class="span-10 offset-1">
  <%= form_for(@post, :html => { :style => 'background: none;', :style => 'border: none;' }) do |f| %>
    <div class="new-post-title">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="new-post-body">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div class="submit"><%= f.submit 'Save Post', class: "btn btn-blue btn-large"  %></div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<div class="Post">
  <h2> <%= @post.title %> </h2>
  <%= @post.body %>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for(@user, :html => { :style => 'background: none;', :style => 'border: none;' }) do |f| %>
  <%= f.label :full_name, "Full Name" %>
  <%= f.text_field :full_name, autofocus: true  %>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <div id="hint"></div>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :permissions %>
  <%= f.select(:permissions, options_for_select([
    ['Administrator', 0],
    ['Developer', 1],
    ['Author', 2]
  ], 0))
  %>

  <%= submit_tag "Sign Up", class: "btn btn-large btn-blue btn-mobile-block" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>